// [Z0·择日八技法基建] 「能算出来的都可搜索」完备性登记表(用户定案 12)。
//
// 制度语义:每个择日技法的 AI 快照段表(AI_EXPORT_PRESET_SECTIONS[技法键])里的**每一段**,
// 必须在本表显式表态,二选一:
//   { types: ['条件类键', …] } —— 该段承载的征象由这些条件类覆盖(键必须真实存在于该技法
//     注册表,哨兵防登记造假);
//   { allTypes: true }        —— 该段=完整盘面,全部条件类都判定于它(如天星「选中时刻星盘」);
//   { exempt: '理由' }        —— 该段无对应条件类,理由 ≥6 字(回显段/叙事段/真 gap 待补皆须
//     写明;「真 gap」型豁免 = 显式欠账,后续轮次补条件类时改登 types)。
// 哨兵 zeriCoverageMap.test.js 机械查:登记段集 ≡ preset 段集双向差空 ——
// **主技法新增快照段(preset 多一段)时此处必须表态,否则机械红**:这就是
// 「原技法算法/征象演进 → 择日强制跟上」的完备性闸。
//
// 新择日技法接入时:在本表加该技法条目(骨架 13 件之一),segment 逐段登记。

export const ZERI_COVERAGE_MAP = {
	// ── 天星择日(32 类,conditionTypes.js) ──
	tianxing: {
		registry: 'conditionTypes',
		sections: {
			'起盘信息': { exempt: '起盘参数回显段,非征象面' },
			'征象搜索配置': { exempt: '择日自身产物段(搜索配置回显)' },
			'征象条件': { exempt: '择日自身产物段(条件树回显)' },
			'命中区间': { exempt: '择日自身产物段(扫描结果)' },
			'选中时刻星盘': { allTypes: true },
		},
	},
	// ── 奇门择日(13 类,qimenConditionTypes.js) ──
	qimenzeri: {
		registry: 'qimenConditionTypes',
		sections: {
			'起盘信息': { exempt: '起盘参数回显段,非征象面' },
			'盘型': { types: ['ju_info'] },
			'全局速览': { types: ['pattern_ji', 'pattern_xiong', 'zhifu', 'zhishi'] },
			'盘面要素': { types: ['tian_gan', 'di_gan', 'door', 'star', 'god', 'palace_flag'] },
			'奇门演卦': { exempt: '演卦断辞叙事段(卦象派生),无独立可判征象量' },
			'八宫详解': { types: ['palace_flag', 'men_gong_relation'] },
			'八宫克应': { types: ['men_gong_relation'] },
			'九宫方盘': { types: ['tian_gan', 'di_gan', 'door', 'star', 'god'] },
			'旺相休囚死·月令能量': { exempt: '真 gap:门星旺衰可判但既有 13 类未覆盖,奇门择日条件补全轮待补(登记即欠账)' },
			'六害总览': { types: ['palace_flag'] },
			'化解方案': { exempt: '化解建议叙事段' },
			'八门化气大阵': { exempt: '化气方位建议叙事段' },
			'用神分论': { exempt: '按事类取用神叙事段' },
			'财富七要': { exempt: '主题判读叙事段' },
			'事业七要': { exempt: '主题判读叙事段' },
			'恋爱姻缘': { exempt: '主题判读叙事段' },
			'孤辰寡宿': { exempt: '真 gap:神煞可判但既有 13 类无神煞类,奇门择日条件补全轮待补' },
			'日家占方（古籍金函系）': { exempt: '日家占方位断辞,非候选时刻征象' },
			'择日搜索配置': { exempt: '择日自身产物段(搜索配置回显)' },
			'择日条件': { exempt: '择日自身产物段(条件树回显)' },
			'命中时辰': { exempt: '择日自身产物段(扫描结果)' },
		},
	},
	// ── [Z1] 黄历择日(17 类,huangliZeriConditionTypes.js;段基底=huangli 日课快照段) ──
	huanglizeri: {
		registry: 'huangliZeriConditionTypes',
		sections: {
			'起盘信息': { types: ['day_ganzhi', 'lunar_day', 'week_day', 'jieqi_day', 'nayin_wuxing'] },
			'今日宜忌': { types: ['yi_has', 'ji_not'] },
			'值神值宿': { types: ['jianchu', 'tianshen_dao', 'zhixiu'] },
			'彭祖百忌': { exempt: '百忌口诀文本(干支定),宜忌类已覆盖用事判定语义' },
			'吉神凶煞': { types: ['jishen_has', 'xiongsha_not', 'nine_star'] },
			'冲煞·胎神·方位': { types: ['chong_shengxiao'] },
			'时辰吉凶': { types: ['good_hour'] },
			'物候·六曜·数九三伏': { types: ['liuyao', 'yuexiang'] },
			'流年年神方位': { exempt: '年神为空间方位指向,非日子筛选量' },
			'年度吉日榜': { exempt: '[Q-458] 默认关候选段:全年 Top 榜(择吉结果面),非当日征象量' },
			'方法说明': { exempt: '算法方法说明叙事段,非征象面' },
			'择吉搜索配置': { exempt: '择日自身产物段(搜索配置回显)' },
			'择吉条件': { exempt: '择日自身产物段(条件树回显)' },
			'命中日段': { exempt: '择日自身产物段(扫描结果)' },
		},
	},
	// ── [Z8] 印度择日(indiaZeriConditionTypes.js;段基底=india 段表) ──
	indiazeri: {
		registry: 'indiaZeriConditionTypes',
		sections: {
			'择时搜索配置': { exempt: '择日自身产物段(搜索配置回显)' },
			'择时条件': { exempt: '择日自身产物段(条件树回显)' },
			'命中时段': { exempt: '择日自身产物段(扫描结果);Panchanga/Lagna/日段/本命组条件面全量在注册表,Dasha 归本命分析(定案14)' },
		},
	},
	qizhengzeri: {
		registry: 'qizhengZeriConditionTypes',
		sections: {
			'起盘信息': { exempt: '起盘参数回显段,非征象面' },
			'七政四余宫位与二十八宿星曜': { types: ['body_in_gong', 'body_in_xiu', 'deg_lord'] },
			'星曜庙旺与星点动态（殿垣庙旺乐喜怒 · 顺逆留伏迟速）': { types: ['dignity', 'speed_state', 'combust'] },
			'神煞': { exempt: '真 gap:七政神煞(日粒度表)首版未建叶,补全轮待议' },
			'大限': { exempt: '大限为本命推演量,不随候选时刻变化' },
			'三主与化曜': { exempt: '[Q-231] 本命三主(命/身/度主)与化曜按生辰派生,不随候选时刻变化' },
			'限法实算': { exempt: '[Q-434] 本命行运法(动限/童限/月限/小限)实算按生辰与行运年,非候选时刻征象' },
			'虚实': { exempt: '虚实为本命判读面(moiraRules),非候选时刻征象' },
			'本命化曜': { exempt: '本命化曜按生辰;候选时刻化曜由 hua_lu 类覆盖' },
			'流年流曜': { exempt: '流年流曜为本命推演量' },
			'政余格局': { exempt: '真 gap:格局判定在主页判读层,组合条件覆盖主判;补全轮待议' },
			'相位': { types: ['body_rel'] },
			'择时搜索配置': { exempt: '择日自身产物段(搜索配置回显)' },
			'择时条件': { exempt: '择日自身产物段(条件树回显)' },
			'命中时段': { exempt: '择日自身产物段(扫描结果)' },
		},
	},
	sanshizeri: {
		registry: 'sanshiZeriConditionTypes',
		sections: {
			'起盘信息': { exempt: '起盘参数回显段,非征象面' },
			'概览': { exempt: '汇总显示层(逐面征象由各家段条件类覆盖)' },
			'太乙': { types: ['ty_yinyang_ju', 'ty_ju_num', 'ty_taiyi_gong', 'ty_wenchang_gong', 'ty_shiji_gong', 'ty_jishen_gong', 'ty_youshen_gong', 'ty_wenchang_taiyi_rel'] },
			'奇门遁甲': { types: ['qm_ju_info', 'qm_zhifu', 'qm_zhishi', 'qm_pillar_ganzhi'] },
			'太乙十六宫': { types: ['ty_gong16_has'] },
			'神煞': { types: ['lr_shensha_at', 'lr_fa_yong'] },
			'大六壬': { types: ['lr_ke_name', 'lr_chuan_zhi', 'lr_chuan_jiang', 'lr_chuan_liuqin', 'lr_yue_jiang_is', 'lr_zhou_ye', 'lr_guiren_pos', 'lr_jiang_at', 'lr_tianpan_at'] },
			'六壬大格': { exempt: '真 gap:大格判定在后端 calcKeCuang,组合条件覆盖主判(Z5 同理)' },
			'六壬小局': { exempt: '同大格:后端判定面,组合条件覆盖' },
			'六壬参考': { exempt: '文献参考层,非征象' },
			'六壬概览': { exempt: '六壬家汇总显示层(逐面已由各段覆盖)' },
			// [Q-451/T-414] 六壬断卦层的七政段(日月五星临支/五行/度/逆行):显示层,择日征象不按七政临支判
			'七政': { exempt: '六壬七政四余合参的显示层(择日条件面无对应征象类;与独立六壬页同段)' },
			'八宫详解': { types: ['qm_door', 'qm_star', 'qm_god', 'qm_tian_gan', 'qm_di_gan', 'qm_palace_flag'] },
			'正北坎宫': { types: ['qm_palace_flag'] },
			'东北艮宫': { types: ['qm_palace_flag'] },
			'正东震宫': { types: ['qm_palace_flag'] },
			'东南巽宫': { types: ['qm_palace_flag'] },
			'正南离宫': { types: ['qm_palace_flag'] },
			'西南坤宫': { types: ['qm_palace_flag'] },
			'正西兑宫': { types: ['qm_palace_flag'] },
			'西北乾宫': { types: ['qm_palace_flag'] },
			'太乙主客定算': { types: ['ty_suan_range', 'ty_suan_parity', 'ty_victory_side', 'ty_dajiang_gong', 'ty_dajiang_same'] },
			'太乙八门与宿曜': { types: ['ty_sanji_men'] },
			'太乙断法': { types: ['ty_geju_kind'] },
			'太乙七大兵法': { types: ['ty_victory_side'] },
			'太乙博弈': { exempt: '博弈扩展面:扫描 gameTheory 恒关,非扫描征象(Z3 同理)' },
			'太乙命法': { exempt: 'style 恒 3 定谳:命法按生辰非候选时刻(Z3 同理)' },
			'太乙命宫行限': { exempt: '命法族段(按生辰),同命法豁免理由' },
			'十二盘式': { types: ['lr_tianpan_at', 'lr_yue_jiang_is', 'lr_zhou_ye'] },
			'常用神煞': { types: ['lr_shensha_at'] },
			'年月神煞': { types: ['lr_shensha_at', 'lr_taisui_god_at'] },
			'课体结构': { types: ['lr_ke_name'] },
			'三传旺衰': { exempt: '真 gap:长生旺衰面首版未建叶(Z5 同理)' },
			'空亡真假': { types: ['lr_chuan_kong'] },
			'旬空落点': { types: ['lr_xun_ding', 'lr_chuan_kong'] },
			'陷空': { exempt: '真 gap(降级留档):analyzeKongLocations 展示层结构,判定表不全(W2 拍板)' },
			'遁干特殊': { types: ['lr_chuan_dungan', 'lr_xun_ding'] },	// [W2 正账]三传遁干新类=该段主判面(xun_ding 只判旬丁/旬空)
			'年命上神': { types: ['lr_bm_shang_jiang'] },
			'毕法（已命中）': { exempt: '真 gap(降级留档):毕法判定表不全,非「能算」面(W2 拍板)' },
			'占断向导': { exempt: '解读文案层,非征象' },
			'奇门九宫方盘': { types: ['qm_door', 'qm_star', 'qm_god'] },
			'奇门旺相休囚死·月令能量': { exempt: '真 gap:旺衰能量面首版未建叶(奇门择日同理)' },
			'奇门六害总览': { types: ['qm_palace_flag'] },
			'奇门化解方案': { exempt: '化解建议文案层,非征象' },
			'奇门八门化气大阵': { types: ['qm_door'] },
			'奇门用神分论': { exempt: '用神分论解读层,组合条件覆盖判定面' },
			'奇门财富七要': { exempt: '主题判读文案层(七要=组合征象解读)' },
			'奇门事业七要': { exempt: '主题判读文案层' },
			'奇门恋爱姻缘': { exempt: '主题判读文案层' },
			'奇门孤辰寡宿': { exempt: '真 gap:孤寡神煞叶首版未建(奇门择日同理)' },
			'紫微四化': { exempt: '三式页紫微四化叠加显示层,非三家扫描盘征象' },
			'择时搜索配置': { exempt: '择日自身产物段(搜索配置回显)' },
			'择时条件': { exempt: '择日自身产物段(条件树回显)' },
			'命中时段': { exempt: '择日自身产物段(扫描结果)' },
		},
	},
	liurengzeri: {
		registry: 'liurengZeriConditionTypes',
		sections: {
			'起盘信息': { exempt: '起盘参数回显段,非征象面' },
			'十二盘式': { types: ['tianpan_at', 'yue_jiang_is', 'zhou_ye'] },
			'十二地盘/十二天盘/十二贵神对应': { types: ['tianpan_at', 'jiang_at', 'guiren_pos'] },
			'四课': { types: ['ke_shang', 'ke_zei'] },
			'三传': { types: ['chuan_zhi', 'chuan_jiang', 'chuan_liuqin', 'chuan_ju', 'chuan_chong_ri'] },
			'行年': { types: ['bm_in_chuan', 'bm_shang_jiang'] },
			'旬日': { types: ['xun_ding', 'day_ganzhi', 'hour_zhi'] },
			'旺衰': { exempt: '真 gap:长生旺衰面可判但首版未建叶,补全轮待议' },
			'基础神煞': { types: ['shensha_at', 'fa_yong'] },
			'干煞': { types: ['shensha_at'] },
			'月煞': { types: ['shensha_at'] },
			'支煞': { types: ['shensha_at'] },
			'岁煞': { types: ['taisui_god_at'] },
			'十二长生': { exempt: '真 gap:十二长生态可判但首版未建叶,补全轮待议' },
			'大格': { exempt: '真 gap:大格判定在后端 calcKeCuang,本地以课名/三传组合条件覆盖主判面;补全轮待议' },
			'小局': { exempt: '同大格:后端判定面,组合条件覆盖' },
			'参考': { exempt: '文献参考层,非征象' },
			'概览': { exempt: '汇总显示层(逐面征象已由各段条件类覆盖)' },
			'常用神煞': { types: ['shensha_at'] },
			'年月神煞': { types: ['shensha_at', 'taisui_god_at'] },
			'课体结构': { types: ['ke_name'] },
			'三传旺衰': { exempt: '真 gap:同旺衰段,首版未建叶' },
			'空亡真假': { types: ['chuan_kong'] },
			'旬空落点': { types: ['xun_ding', 'chuan_kong'] },
			'陷空': { exempt: '真 gap(降级留档):analyzeKongLocations 展示层结构,判定表不全(W2 拍板)' },
			'遁干特殊': { types: ['chuan_dungan', 'xun_ding'] },	// [W2 正账]
			'年命上神': { types: ['bm_shang_jiang'] },
			'占断向导': { exempt: '解读文案层,非征象' },
			'毕法（已命中）': { exempt: '真 gap(降级留档):毕法判定表不全,非「能算」面(W2 拍板)' },
			'七政': { exempt: '七政临宫层=后端星历专属,本地扫描无此供数' },
			'取象': { exempt: '象意库文案层(doctrine 默认关)' },
			'择时搜索配置': { exempt: '择日自身产物段(搜索配置回显)' },
			'择时条件': { exempt: '择日自身产物段(条件树回显)' },
			'命中时段': { exempt: '择日自身产物段(扫描结果)' },
		},
	},
	ziweizeri: {
		registry: 'ziweiZeriConditionTypes',
		sections: {
			'起盘信息': { exempt: '起盘参数回显段,非征象面' },
			'宫位总览': { types: ['ming_gong_zhi', 'ming_zhu_xing', 'ming_changsheng', 'star_in_gong', 'star_in_zhi', 'star_brightness', 'sihua_star', 'sihua_in_gong', 'sihua_dui_ming', 'wuxing_ju', 'life_master', 'body_master', 'doujun_zhi'] },
			'身宫': { types: ['shen_zhu_xing'] },
			'来因宫': { exempt: '真 gap:来因宫(生年干落宫)可判但首版未建叶,补全轮待议' },
			'八字大运': { exempt: '大运为本命推演量,不随候选时刻语义成立(lite 引擎亦不产)' },
			'命中格局': { types: ['star_tong_gong', 'sanfang_has', 'liuji_count', 'liusha_count', 'kong_jie_ming'] },
			// [Windows #80] 运限概览:与「运限」同族(全大限×流年映射表),同理由豁免。
			'运限概览': { exempt: '运限为本命推演量,非候选时刻征象' },
			'运限': { exempt: '运限为本命推演量,非候选时刻征象' },
			'流派叠层': { exempt: '多流派四化对照显示层;判定面四化条件随当前流派单值(sihua_* 类)' },
			'择时搜索配置': { exempt: '择日自身产物段(搜索配置回显)' },
			'择时条件': { exempt: '择日自身产物段(条件树回显)' },
			'命中时段': { exempt: '择日自身产物段(扫描结果)' },
		},
	},
	taiyizeri: {
		registry: 'taiyiZeriConditionTypes',
		sections: {
			'起盘信息': { exempt: '起盘参数回显段,非征象面' },
			'起盘': { types: ['yinyang_ju', 'ju_num'] },
			'太乙盘': { types: ['gong16_has'] },
			'太乙诸神': { types: ['taiyi_gong', 'wenchang_gong', 'shiji_gong', 'jishen_gong', 'youshen_gong', 'wenchang_taiyi_rel'] },
			'风游': { types: ['gong16_has'] },
			'主客定算': { types: ['suan_range', 'suan_parity', 'victory_side', 'dajiang_gong', 'dajiang_same'] },
			'十二神': { types: ['gong16_has'] },
			'八门与宿曜': { types: ['sanji_men'] },
			'断法': { types: ['geju_kind'] },
			'七大兵法': { types: ['victory_side'] },
			'博弈': { exempt: '博弈扩展面:扫描 options gameTheory 恒 0(工作台不开此档),非扫描征象' },
			'命法': { exempt: 'style 恒 3 定谳:命法按生辰非候选时刻,不是择日扫描对象' },
			'命宫行限': { exempt: '命法族段(按生辰),同命法豁免理由' },
			'十六宫标记': { types: ['gong16_has'] },
			'择时搜索配置': { exempt: '择日自身产物段(搜索配置回显)' },
			'择时条件': { exempt: '择日自身产物段(条件树回显)' },
			'命中时段': { exempt: '择日自身产物段(扫描结果)' },
		},
	},
	// ── [Z2] 八字择日(baziZeriConditionTypes.js;段基底=bazi 段表) ──
	bazizeri: {
		registry: 'baziZeriConditionTypes',
		sections: {
			'起盘信息': { exempt: '起盘参数回显段,非征象面' },
			'四柱与三元': { types: ['day_ganzhi', 'hour_ganzhi', 'month_year_gz', 'nayin_wuxing', 'xunkong', 'changsheng'] },
			'神煞（四柱与三元）': { types: ['shensha_has', 'shensha_not'] },
			'五行力量': { types: ['wuxing_day', 'wuxing_presence'] },
			'格局·用神': { types: ['bm_xiyong'], },
			'盲派结构': { exempt: '真 gap:盲派做功结构可判但候选时刻语义弱(本命分析面),补全轮待议' },
			'月令司令（分野）': { types: ['jieqi_month'] },
			'干支合冲': { types: ['zhi_relation', 'gan_wuhe', 'sanhe_ju', 'bm_bu_chong', 'bm_he'] },
			'大运': { exempt: '大运为本命推演量,不随候选时刻变化' },
			'流年行运概略': { exempt: '行运为本命推演量,不随候选时刻变化' },
			'多运限·指定时段': { exempt: '本命运限工具段,非候选时刻征象' },
			'择时搜索配置': { exempt: '择日自身产物段(搜索配置回显)' },
			'择时条件': { exempt: '择日自身产物段(条件树回显)' },
			'命中时段': { exempt: '择日自身产物段(扫描结果)' },
		},
	},
};
